name: Build LibreELEC for Phicomm N1

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 签出代码
      uses: actions/checkout@v4
      with:
        repository: LibreELEC/LibreELEC.tv
        fetch-depth: 1

    - name: 安装编译依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          make gcc g++ git texinfo \
          build-essential curl wget \
          gperf bison flex libtool \
          libxml2-utils xsltproc \
          bc swig python3 python3-distutils \
          libssl-dev libcap-dev \
          ccache \
          xfonts-utils \
          rdfind \
          libparse-yapp-perl \
          libxml-parser-perl \
          patchutils \
          lzop

    - name: 执行编译
      run: |
        PROJECT=Amlogic ARCH=aarch64 DEVICE=AMLGX make image



    - name: 生成并推送新版本标签
      if: github.event_name == 'workflow_dispatch'
      run: |
        # 获取最新版本号并递增（例如从日期生成）
        NEW_TAG="nightly-$(date +'%Y%m%d')"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag $NEW_TAG
        git push origin $NEW_TAG
